name: Run PAR Performance Tests (K6)

on:
  workflow_dispatch:

jobs:
  run-perf-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install K6
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg2
          curl -s https://dl.k6.io/key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/k6-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install -y k6

      - name: 🛠 Set PERF_URL for K6
        run: |
          echo "PERF_URL=https://www.timztos.co.uk/" >> $GITHUB_ENV

      - name: Run Performance Test and Generate Report
        run: npm run perf:run

      - name: Upload Performance Report (HTML)
        uses: actions/upload-artifact@v4
        with:
          name: k6-html-report
          path: k6-results/summary.html
          if-no-files-found: warn
          compression-level: 6
          overwrite: false


      - name: Upload Raw Summary (JSON)
        uses: actions/upload-artifact@v4
        with:
          name: k6-summary-json
          path: k6-results/summary.json
